/*
Author     :  Gurrala Madhu <gurralamadhu652@gmail.com>
Purpose    :  Miniproject on Student Performance
start Date :  10/04/2025
End Date   :  10/04/2025
*/

-- First we created a schema/Database E-Commerce Sales Data
create database `E-Commerce Sales Data`;


-- USE KEYWORD
-- USE Keyword is used to create the active session database

use `E-Commerce Sales Data`;

-- Then i have loaded the dataset into the database/schmea E-Commerce Sales Data using table data import wizard

/*
 Describe Keyword
Describe keyword tells about the structure of columns including column names ,Data type of columns and Constraints.
*/

describe `Amazon Sales`;

-- ALTER KEYWORD
-- ALTER Keyword is used to modify the definition of table and modify the defination of columns.
-- ALTER KEYWORD USE CASES 
-- RENAME the existing table
-- ADD a new column
-- DROP the existing columns
-- MODIFY the existing columns
-- To change the order of columns 

-- here the data type of date column is changed to date data type from text
alter table `Amazon Sales` 
add column date_ordered date after `Order ID`;
update `Amazon Sales` set date_ordered=str_to_date(Date,'%m-%d-%y');

-- Drop Keyword is used to drop the table or column or database
alter table `Amazon Sales` drop column Date;
alter table `Amazon Sales` drop column `Unnamed: 22` ;

-- Retriving the total orders that had been done from country india
SELECT 
    COUNT(`Order ID`) AS ORDERS_INDIA
FROM
    `Amazon Sales`
WHERE
    `ship-country` = 'IN';

-- retrieving count of orders that have been taken place from different states
SELECT 
    `ship-state`, COUNT(`Order ID`) AS ORDERS
FROM
    `Amazon Sales`
GROUP BY `ship-state`
ORDER BY ORDERS DESC;


-- GROUP BY KEYWORD
-- GROUP BY Keyword is used to group rows that have the same values in a specified columns.
-- It is often used with aggregate functions (like COUNT, SUM, AVG, MAX, MIN) to perform calculations on each group of data.

-- Retrieving the count of Orders taken place in different cities

SELECT 
    `ship-city`,COUNT(`Order ID`) AS ORDERS
FROM
    `Amazon Sales`
GROUP BY `ship-city`;

-- Retrieving the orders that have been shipped between business to business
SELECT 
    B2B, COUNT(B2B) AS BUSINESS_TO_BUSINESS
FROM
    `Amazon Sales`
GROUP BY B2B;

-- HERE ONLY 50 ORDERS ARE SHIPPED BETWEEN TWO BUSINESS

-- RETRIEVING TOTAL AMOUNT / REVENUE GENERATED BY THE DIFFERENT CATEGORIES AND HIGHEST REVENUE GENERATED CATEGORY
SELECT 
    Category, SUM(Amount) AS REVENUE
FROM
    `Amazon Sales`
GROUP BY Category
ORDER BY REVENUE DESC -- ODERBY IS USED TO CHANGE ORDER OF A ATTRIBUTE
LIMIT 1; -- LIMIT IS USED TO LIMIT THE DATA

-- CHECKING THE COUNT OF DIFFERENT COURIERS STATUS 
SELECT 
    `Courier Status`, COUNT(`Courier Status`) as courier_status
FROM
    `Amazon Sales`
GROUP BY `Courier Status`
order by courier_status desc;

-- it shows that the coriers shipped are more but there is a issue of that some couriers not having any status

-- Retrieve the sales that have been taken place by different categories where the courier status is shipped

SELECT 
    Category, COUNT(Qty) as Total_sales
FROM
    `Amazon Sales`
    where `Courier Status`='shipped'
GROUP BY Category
order by Total_sales desc;

-- Retrieve the Category that has most quantity of sales and amount collected by it as revenue.

SELECT 
    Category, COUNT(Qty) as Total_sales,sum(Amount) as revenue
FROM
    `Amazon Sales`
GROUP BY Category
order by Total_sales desc
limit 1;

-- Retrive the orders that have been taken place on different ship service levels

SELECT 
    `ship-service-level`, COUNT(`Order ID`)
FROM
    `Amazon Sales`
WHERE
    `Courier Status` = 'shipped'
GROUP BY `ship-service-level`;

-- Check the status of orders that have been ordered from states TELANGANA ,Tamilnadu , UTTAR PRADESH, KERALA,ANDDHRA PRADESH
SELECT 
    `ship-state`, COUNT(`Order ID`) as Total_sales
FROM
    `Amazon Sales`
WHERE
    `ship-state` IN ('TELANGANA' , 'Tamilnadu',
        'UTTAR PRADESH',
        'KERALA',
        'ANDDHRA PRADESH')
        AND Status = 'shipped'
GROUP BY `ship-state`;

-- Retrieve the top 5 average revenue generated by the different states to amazon sum of sales happened

SELECT 
    `ship-state`,
    AVG(Amount) AS Total_revenue,
    SUM(`Order ID`) AS Total_sales
FROM
    `Amazon sales`
WHERE
    Status = 'shipped'
GROUP BY `ship-state`
order by Total_revenue desc;

-- Retrieve the orders that have been taken place day wise
SELECT 
    DAYNAME(date_ordered) AS Days,
    COUNT(`Order ID`) AS Sales_day,
    SUM(Amount) AS Revenue_Day
FROM
    `Amazon sales`
WHERE
    Status = 'shipped'
GROUP BY Days
ORDER BY Revenue_Day desc , Sales_day desc;

-- Rtrieve order id,category,total amount, where in category i want only saree,set,kurta and amount>500,and status is shipped
SELECT 
     Category, SUM(Amount) AS Total_amount
FROM
    `Amazon sales`
WHERE
    Category IN ('Saree' , 'Set', 'Kurta')
        AND Amount='>500'
        AND Status = 'shipped'
group by Category
ORDER BY Total_amount DESC;

-- Retrieve the month wise sales and amount collected as revenue ship-service-level is Standard

select monthname(date_ordered) as Month,count(`Order ID`) AS Total_sales,SUM(Qty) as Orders,Sum(Amount) as Revenue
where `ship-service-level`='Standard'
group by Month
order by Total_sales desc,Orders desc,Revenue desc;

-- JOINS 
--  Combine the two tables using all types of joins (Inner Join, Left Join, Right Join, and Cross Join).

-- NOTE: To combine the two tables we use joins.
/* JOINS
There are 6 types of joins.They are 
1.INNER JOIN
2.LEFT JOIN
3.RIGHT JOIN
4.FULL JOIN
5.CROSS JOIN
6.SELF JOIN
 */
 -- ON KEYWORD
-- ON Keyword is primarily used to join the two tables based on condition 
-- The ON keyword is used in INNER JOIN, LEFT JOIN, RIGHT JOIN, and FULL JOIN to define the relationship between columns in the joined tables.

-- 1.INNER JOIN
-- INNER JOIN returns the records that have matching values in the both tables.
-- No unmatched rows will be displayed.

-- Retrieve the both datasets revenue and compare them
SELECT 
    sum(si.Amount) AS Total_Revenue,
    sum(sm.amount) AS Total_revenue2
FROM
    `Amazon Sales` as si
        INNER JOIN
    `Amazon Sale Data` as sm ON si.`ship-country` = sm.`ship_country`;
    
-- 2.LEFT JOIN
-- Returns all records from the left table, and the matched records from the right table. 
-- Returns unmatched right table rows with null values. 
-- It is also called as LEFT OUTER JOIN.

SELECT 
    count(si.`Order ID`) AS Sales,
    AVG(si.Amount) AS Total_Revenue,
    count(sm.`order_id`) AS Sales1,
    AVG(sm.amount) AS Total_revenue2
FROM
    `Amazon Sales` AS si
        LEFT JOIN
    `Amazon Sale Data` AS sm ON si.`ship-country` = sm.`ship_country`;
    
    
    -- 3.RIGHT JOIN
-- Returns all records from the right table, and the matched records from the left table. 
-- Returns unmatched left table rows with null values.
-- It is also called as RIGHT OUTER JOIN.


    SELECT 
    count(si.`Order ID`) AS Sales,
    AVG(si.Amount) AS Total_Revenue,
    count(sm.`order_id`) AS Sales1,
    AVG(sm.amount) AS Total_revenue2
FROM
    `Amazon Sales` AS si
        Right JOIN
    `Amazon Sale Data` AS sm ON si.`ship-country` = sm.`ship_country`;
    
    -- 4.FULL JOIN
-- Returns all records when there is a match in either left (table1) or right (table2) table records. 
-- Also returns null if there is no match.
-- It is also called as FULL OUTER JOIN.
-- Not all databases support FULL JOIN (e.g., MySQL). In such cases, you can simulate it using LEFT JOIN and RIGHT JOIN with UNION.

-- 5.CROSS JOIN
-- Returns the Cartesian product of both tables (i.e., every combination of rows).
-- No matching condition.
-- Returns all possible row combinations.

SELECT 
    si.*, sm.*
FROM
    `Amazon Sales` AS si
        CROSS JOIN
    `Amazon Sale Data` AS sm;
    
-- Retrieve the sum of sales from both the tables where status is shipped in table 1 and fulfillment is amazon in table 2

-- SUB QUERY

SELECT 
    count(`Order ID`) AS Sales, AVG(Amount) AS Total_Revenue
FROM
    `Amazon Sales`
WHERE
    `ship-country` IN ( SELECT 
            ship_country
        FROM
            `Amazon Sale Data`);



-- RETRIEVE THE ORDER ID,STATUS,AMOUNT,QTY FROM BOTH THE TABLES USING ANY JOIN/SUBQUERY
SELECT 
    `Order ID` , Status, Amount, Qty
FROM
    `Amazon Sales`
WHERE
    `ship-country` IN (SELECT 
            ship_country
        FROM
            `Amazon Sale Data`);
            
